CREATE TABLE produto (
id SERIAL NOT NULL,
modelo VARCHAR(20) NOT NULL,
marca VARCHAR(20) NOT NULL,
categoria VARCHAR(20) NOT NULL,
preco DECIMAL(18,4) NOT NULL,
quant INT NOT NULL,
nota DECIMAL(8,2) NOT NULL,
PRIMARY KEY (id)
);